// real-portfolio-project/src/components/ArchitectureShowcase.jsx
import React, { useState } from 'react';
import { TiltCard } from './TiltCard';
import { sounds } from '../utils/audio';
import { Layers, ShieldCheck, Cpu, Database, Server, Terminal, Workflow, ArrowRight } from 'lucide-react';

export const ArchitectureShowcase = () => {
  const [selectedNode, setSelectedNode] = useState(0);

  const nodes = [
    {
      id: 'angular-ui',
      title: 'Angular UI',
      sub: 'Client App',
      category: 'FRONTEND',
      color: '#dd0031',
      details: 'Built with Angular 19 Standalone Components, Signal State Management, Dynamic Multilanguage Pipes, and Reactive Forms. Intercepts HTTP requests to inject JWT Auth Headers and Tenant Context headers.'
    },
    {
      id: 'api-gateway',
      title: 'API Gateway',
      sub: 'Spring Cloud Gateway',
      category: 'ROUTING',
      color: '#8b5cf6',
      details: 'Centralized edge gateway performing CORS configuration, Global Exception Handling, JWT token validation, rate limiting, and dynamic load-balanced request forwarding to microservice instances.'
    },
    {
      id: 'microservices',
      title: 'Microservices',
      sub: 'Spring Boot + Eureka',
      category: 'BACKEND',
      color: '#10b981',
      details: 'Decoupled Spring Boot microservices (Auth, Employee, Department, Notification, Order, Inventory) incorporating Spring Data JPA, Spring Security RBAC, NVIDIA AI integration, and Eureka discovery.'
    },
    {
      id: 'postgres-db',
      title: 'PostgreSQL',
      sub: 'Multi-tenant Schema',
      category: 'DATA LAYER',
      color: '#3b82f6',
      details: 'PostgreSQL dynamic Schema-per-Tenant isolation for Winfocus Pharma SaaS, alongside MSSQL enterprise databases equipped with Stored Procedures, Non-Clustered Indexes, and Synonyms for Hyderabad Metro AMS.'
    },
    {
      id: 'docker-k8s',
      title: 'Docker / K8s',
      sub: 'Orchestration',
      category: 'CONTAINERS',
      color: '#0284c7',
      details: 'Containerized Docker microservice images orchestrated across Kubernetes pods with rolling updates, environment secret injection, and automated health checks.'
    }
  ];

  const activeNode = nodes[selectedNode];

  return (
    <section id="architecture" className="section-wrapper">
      <div className="section-container">
        {/* Header */}
        <div className="section-header">
          <span className="section-tag">System Design</span>
          <h2 className="section-title">Enterprise <span className="accent-text">Architecture</span></h2>
          <p className="section-sub">Production microservice topology — click any node to explore implementation details</p>
          <div className="title-line"></div>
        </div>

        {/* SVG Flow Diagram Wrapper matching Screenshot */}
        <div className="arch-diagram-wrapper glass-card">
          <svg className="arch-svg" viewBox="0 0 1020 220" xmlns="http://www.w3.org/2000/svg">
            <defs>
              <linearGradient id="flowLineGrad" x1="0%" y1="0%" x2="100%" y2="0%">
                <stop offset="0%" stopColor="#dd0031" stopOpacity="0.8" />
                <stop offset="35%" stopColor="#8b5cf6" stopOpacity="0.8" />
                <stop offset="70%" stopColor="#10b981" stopOpacity="0.8" />
                <stop offset="100%" stopColor="#3b82f6" stopOpacity="0.8" />
              </linearGradient>
            </defs>

            {/* Top Feedback Loop Arc: CI/CD Trigger */}
            <path
              d="M 880 50 Q 880 18 510 18 Q 300 18 290 50"
              fill="none"
              stroke="rgba(240, 80, 50, 0.4)"
              strokeWidth="1.5"
              strokeDasharray="4 4"
            />
            <text x="510" y="14" fill="rgba(240,80,50,0.7)" fontSize="9.5" fontFamily="monospace" text-anchor="middle">
              CI/CD deploy trigger
            </text>

            {/* Connection Lines */}
            <line x1="165" y1="110" x2="215" y2="110" stroke="url(#flowLineGrad)" strokeWidth="2" strokeDasharray="5 3" />
            <text x="190" y="104" fill="rgba(167,139,250,0.7)" fontSize="8.5" fontFamily="monospace" text-anchor="middle">HTTP</text>

            <line x1="365" y1="110" x2="415" y2="110" stroke="url(#flowLineGrad)" strokeWidth="2" strokeDasharray="5 3" />
            <text x="390" y="104" fill="rgba(167,139,250,0.7)" fontSize="8.5" fontFamily="monospace" text-anchor="middle">JWT</text>

            <line x1="565" y1="110" x2="615" y2="110" stroke="url(#flowLineGrad)" strokeWidth="2" strokeDasharray="5 3" />
            <line x1="765" y1="110" x2="815" y2="110" stroke="url(#flowLineGrad)" strokeWidth="2" strokeDasharray="5 3" />

            {/* Glowing Packet */}
            <circle r="4.5" fill="#38bdf8">
              <animateMotion path="M 165,110 L 815,110" dur="4s" repeatCount="indefinite" />
            </circle>

            {/* Node 0: Angular UI */}
            <g className="svg-node-group" onClick={() => { sounds.playClick(); setSelectedNode(0); }} style={{ cursor: 'pointer' }}>
              <rect x="20" y="50" width="145" height="120" rx="14" fill={selectedNode === 0 ? 'rgba(221,0,49,0.18)' : 'rgba(221,0,49,0.06)'} stroke={selectedNode === 0 ? '#dd0031' : 'rgba(221,0,49,0.4)'} strokeWidth={selectedNode === 0 ? '2' : '1'} />
              <circle cx="92.5" cy="85" r="18" fill="rgba(221,0,49,0.15)" stroke="#dd0031" strokeWidth="1" />
              <text x="92.5" y="118" textAnchor="middle" fill="#dd0031" fontSize="8" fontWeight="800" fontFamily="monospace" letterSpacing="0.8">FRONTEND</text>
              <text x="92.5" y="136" textAnchor="middle" fill="#f1f5f9" fontSize="13" fontWeight="800" fontFamily="var(--font-display)">Angular UI</text>
              <text x="92.5" y="152" textAnchor="middle" fill="#94a3b8" fontSize="10" fontWeight="500">Client App</text>
            </g>

            {/* Node 1: API Gateway */}
            <g className="svg-node-group" onClick={() => { sounds.playClick(); setSelectedNode(1); }} style={{ cursor: 'pointer' }}>
              <rect x="220" y="50" width="145" height="120" rx="14" fill={selectedNode === 1 ? 'rgba(139,92,246,0.18)' : 'rgba(139,92,246,0.06)'} stroke={selectedNode === 1 ? '#8b5cf6' : 'rgba(139,92,246,0.4)'} strokeWidth={selectedNode === 1 ? '2' : '1'} />
              <circle cx="292.5" cy="85" r="18" fill="rgba(139,92,246,0.15)" stroke="#8b5cf6" strokeWidth="1" />
              <text x="292.5" y="118" textAnchor="middle" fill="#a78bfa" fontSize="8" fontWeight="800" fontFamily="monospace" letterSpacing="0.8">ROUTING</text>
              <text x="292.5" y="136" textAnchor="middle" fill="#f1f5f9" fontSize="13" fontWeight="800" fontFamily="var(--font-display)">API Gateway</text>
              <text x="292.5" y="152" textAnchor="middle" fill="#94a3b8" fontSize="10" fontWeight="500">Spring Cloud Gateway</text>
            </g>

            {/* Node 2: Microservices */}
            <g className="svg-node-group" onClick={() => { sounds.playClick(); setSelectedNode(2); }} style={{ cursor: 'pointer' }}>
              <rect x="420" y="50" width="145" height="120" rx="14" fill={selectedNode === 2 ? 'rgba(16,185,129,0.18)' : 'rgba(16,185,129,0.06)'} stroke={selectedNode === 2 ? '#10b981' : 'rgba(16,185,129,0.4)'} strokeWidth={selectedNode === 2 ? '2' : '1'} />
              <circle cx="492.5" cy="85" r="18" fill="rgba(16,185,129,0.15)" stroke="#10b981" strokeWidth="1" />
              <text x="492.5" y="118" textAnchor="middle" fill="#10b981" fontSize="8" fontWeight="800" fontFamily="monospace" letterSpacing="0.8">BACKEND</text>
              <text x="492.5" y="136" textAnchor="middle" fill="#f1f5f9" fontSize="13" fontWeight="800" fontFamily="var(--font-display)">Microservices</text>
              <text x="492.5" y="152" textAnchor="middle" fill="#94a3b8" fontSize="10" fontWeight="500">Spring Boot + Eureka</text>
            </g>

            {/* Node 3: PostgreSQL */}
            <g className="svg-node-group" onClick={() => { sounds.playClick(); setSelectedNode(3); }} style={{ cursor: 'pointer' }}>
              <rect x="620" y="50" width="145" height="120" rx="14" fill={selectedNode === 3 ? 'rgba(59,130,246,0.18)' : 'rgba(59,130,246,0.06)'} stroke={selectedNode === 3 ? '#3b82f6' : 'rgba(59,130,246,0.4)'} strokeWidth={selectedNode === 3 ? '2' : '1'} />
              <circle cx="692.5" cy="85" r="18" fill="rgba(59,130,246,0.15)" stroke="#3b82f6" strokeWidth="1" />
              <text x="692.5" y="118" textAnchor="middle" fill="#3b82f6" fontSize="8" fontWeight="800" fontFamily="monospace" letterSpacing="0.8">DATA LAYER</text>
              <text x="692.5" y="136" textAnchor="middle" fill="#f1f5f9" fontSize="13" fontWeight="800" fontFamily="var(--font-display)">PostgreSQL</text>
              <text x="692.5" y="152" textAnchor="middle" fill="#94a3b8" fontSize="10" fontWeight="500">Multi-tenant Schema</text>
            </g>

            {/* Node 4: Docker / K8s */}
            <g className="svg-node-group" onClick={() => { sounds.playClick(); setSelectedNode(4); }} style={{ cursor: 'pointer' }}>
              <rect x="820" y="50" width="145" height="120" rx="14" fill={selectedNode === 4 ? 'rgba(2,132,199,0.18)' : 'rgba(2,132,199,0.06)'} stroke={selectedNode === 4 ? '#0284c7' : 'rgba(2,132,199,0.4)'} strokeWidth={selectedNode === 4 ? '2' : '1'} />
              <circle cx="892.5" cy="85" r="18" fill="rgba(2,132,199,0.15)" stroke="#0284c7" strokeWidth="1" />
              <text x="892.5" y="118" textAnchor="middle" fill="#38bdf8" fontSize="8" fontWeight="800" fontFamily="monospace" letterSpacing="0.8">CONTAINERS</text>
              <text x="892.5" y="136" textAnchor="middle" fill="#f1f5f9" fontSize="13" fontWeight="800" fontFamily="var(--font-display)">Docker / K8s</text>
              <text x="892.5" y="152" textAnchor="middle" fill="#94a3b8" fontSize="10" fontWeight="500">Orchestration</text>
            </g>
          </svg>

          <div className="diagram-click-hint">
            <span>👆 Click any node to explore its implementation details</span>
          </div>
        </div>

        {/* Selected Node Inspector Panel */}
        <TiltCard className="node-inspector-panel glass-card">
          <div className="inspector-header">
            <div className="inspector-icon" style={{ color: activeNode.color, background: `${activeNode.color}20` }}>
              <Workflow size={24} />
            </div>
            <div>
              <span className="inspector-badge" style={{ color: activeNode.color }}>{activeNode.category} COMPONENT</span>
              <h3>{activeNode.title} — {activeNode.sub}</h3>
            </div>
          </div>

          <p className="inspector-desc">{activeNode.details}</p>

          <div className="inspector-meta-row">
            <div className="meta-pill">
              <ShieldCheck size={14} className="icon-green" />
              <span>Production Validated</span>
            </div>
            <div className="meta-pill">
              <Layers size={14} className="icon-purple" />
              <span>{activeNode.category}</span>
            </div>
          </div>
        </TiltCard>
      </div>

      <style>{`
        .arch-diagram-wrapper {
          padding: 24px;
          margin-bottom: 28px;
          overflow-x: auto;
        }

        .arch-svg {
          width: 100%;
          min-width: 900px;
          height: auto;
        }

        .diagram-click-hint {
          text-align: center;
          margin-top: 12px;
          font-size: 13px;
          color: var(--text-secondary);
          font-weight: 600;
        }

        .node-inspector-panel {
          padding: 32px;
        }

        .inspector-header {
          display: flex;
          align-items: center;
          gap: 16px;
          margin-bottom: 16px;
        }

        .inspector-icon {
          width: 54px;
          height: 54px;
          border-radius: 16px;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .inspector-badge {
          font-size: 11px;
          font-weight: 800;
          text-transform: uppercase;
          letter-spacing: 1px;
        }

        .inspector-header h3 {
          font-family: var(--font-display);
          font-size: 20px;
          font-weight: 800;
        }

        .inspector-desc {
          font-size: 15px;
          color: var(--text-secondary);
          line-height: 1.7;
          margin-bottom: 24px;
        }

        .inspector-meta-row {
          display: flex;
          gap: 16px;
        }

        .meta-pill {
          display: flex;
          align-items: center;
          gap: 8px;
          font-size: 13px;
          font-weight: 600;
          padding: 6px 14px;
          border-radius: 12px;
          background: color-mix(in srgb, var(--card-bg) 80%, transparent);
          border: 1px solid var(--border-color);
        }

        .icon-green { color: #10b981; }
        .icon-purple { color: #8b5cf6; }
      `}</style>
    </section>
  );
};

// my-portfolio/src/app/components/architecture-showcase/architecture-showcase.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { PortfolioService } from '../../services/Portfolio.service';

@Component({
  selector: 'app-architecture-showcase',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './architecture-showcase.component.html',
  styleUrl: './architecture-showcase.component.css'
})
export class ArchitectureShowcaseComponent {
  constructor(public ps: PortfolioService) {}

  activeNode: number | null = null;

  steps = [
    {
      title: 'Angular UI Client',
      icon: 'fab fa-angular',
      color: '#dd0031',
      desc: 'Modern, highly responsive client frontend featuring lazy-loaded routes, state signals, and reactive forms.'
    },
    {
      title: 'API Gateway',
      icon: 'fas fa-route',
      color: '#a78bfa',
      desc: 'Central entrance routing client requests. Applies custom JWT authentication filters, CORS, and request rate-limiting.'
    },
    {
      title: 'Spring Boot Services',
      icon: 'fas fa-server',
      color: '#6db33f',
      desc: 'Resilient Microservices registry via Eureka. Includes separate Inventory, Billing, and Core Auth services interacting via OpenFeign.'
    },
    {
      title: 'Database Schema Router',
      icon: 'fas fa-database',
      color: '#336791',
      desc: 'Dynamic PostgreSQL connection routing. Isolates clinics into isolated private schemas per tenant organization.'
    },
    {
      title: 'Docker & Kubernetes',
      icon: 'fab fa-docker',
      color: '#326ce5',
      desc: 'Microservices containerized as Docker layers and orchestrated within a highly fault-tolerant local Kubernetes pod network.'
    },
    {
      title: 'GitHub Actions CI/CD',
      icon: 'fab fa-github-alt',
      color: '#f05032',
      desc: 'Automated continuous integration pipeline testing compile status, compiling images, and pushing to secure deployment registries.'
    }
  ];

  selectNode(index: number | null) {
    this.activeNode = index;
  }
}

<section class="arch-section section-alt">
  <div class="section-container">

    <!-- Header -->
    <div class="section-header" data-aos="fade-up">
      <span class="section-tag">System Design</span>
      <h2 class="section-title">Enterprise <span class="accent">Architecture</span></h2>
      <p class="section-sub">Production microservice topology — click any node to explore implementation details</p>
      <div class="title-line"></div>
    </div>

    <!-- SVG FLOW DIAGRAM -->
    <div class="diagram-wrapper glass-card">
      <svg class="arch-svg" viewBox="0 0 1060 260" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid meet">
        <defs>
          <!-- Arrow marker -->
          <marker id="arrow" markerWidth="8" markerHeight="8" refX="6" refY="3" orient="auto">
            <path d="M0,0 L0,6 L8,3 z" fill="rgba(148,163,184,0.5)"/>
          </marker>
          <!-- Glow filters per node color -->
          <filter id="glow-red" x="-30%" y="-30%" width="160%" height="160%">
            <feGaussianBlur stdDeviation="4" result="blur"/>
            <feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
          </filter>
          <filter id="glow-purple" x="-30%" y="-30%" width="160%" height="160%">
            <feGaussianBlur stdDeviation="4" result="blur"/>
            <feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
          </filter>
          <filter id="glow-green" x="-30%" y="-30%" width="160%" height="160%">
            <feGaussianBlur stdDeviation="4" result="blur"/>
            <feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
          </filter>
          <filter id="glow-blue" x="-30%" y="-30%" width="160%" height="160%">
            <feGaussianBlur stdDeviation="4" result="blur"/>
            <feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge>
          </filter>
          <!-- Subtle grid pattern -->
          <pattern id="grid" width="30" height="30" patternUnits="userSpaceOnUse">
            <path d="M 30 0 L 0 0 0 30" fill="none" stroke="rgba(255,255,255,0.025)" stroke-width="0.5"/>
          </pattern>
        </defs>

        <!-- Background grid -->
        <rect width="1060" height="260" fill="url(#grid)" rx="16"/>

        <!-- ── Connection lines ── -->
        <!-- Angular → Gateway -->
        <line x1="168" y1="130" x2="238" y2="130" stroke="rgba(148,163,184,0.35)" stroke-width="1.5" stroke-dasharray="4 3" marker-end="url(#arrow)"/>
        <!-- Gateway → Services -->
        <line x1="388" y1="130" x2="458" y2="130" stroke="rgba(148,163,184,0.35)" stroke-width="1.5" stroke-dasharray="4 3" marker-end="url(#arrow)"/>
        <!-- Services → DB -->
        <line x1="608" y1="130" x2="678" y2="130" stroke="rgba(148,163,184,0.35)" stroke-width="1.5" stroke-dasharray="4 3" marker-end="url(#arrow)"/>
        <!-- DB → Docker -->
        <line x1="828" y1="130" x2="898" y2="130" stroke="rgba(148,163,184,0.35)" stroke-width="1.5" stroke-dasharray="4 3" marker-end="url(#arrow)"/>
        <!-- Docker → CI/CD (curve from bottom) -->
        <path d="M 940 195 Q 940 240 960 240 Q 980 240 980 220" stroke="rgba(240,80,50,0.4)" stroke-width="1.5" fill="none" stroke-dasharray="4 3" marker-end="url(#arrow)"/>
        <!-- CI/CD back to Gateway (feedback loop top) -->
        <path d="M 980 60 Q 980 24 580 24 Q 320 24 310 60" stroke="rgba(240,80,50,0.25)" stroke-width="1" fill="none" stroke-dasharray="3 4"/>
        <!-- Label on feedback loop -->
        <text x="530" y="18" fill="rgba(240,80,50,0.55)" font-size="9" font-family="monospace" text-anchor="middle">CI/CD deploy trigger</text>

        <!-- JWT label on Gateway→Services arrow -->
        <text x="423" y="124" fill="rgba(167,139,250,0.7)" font-size="8.5" font-family="monospace" text-anchor="middle">JWT</text>

        <!-- ── NODE 0: Angular UI ── -->
        <g class="svg-node" (click)="selectNode(0)" [class.svg-active]="selectedNodeIndex===0" style="cursor:pointer">
          <rect x="20" y="72" width="148" height="116" rx="14"
            fill="rgba(221,0,49,0.06)" stroke="rgba(221,0,49,0.35)" stroke-width="1.5"
            [attr.stroke]="selectedNodeIndex===0 ? '#dd0031' : 'rgba(221,0,49,0.35)'"
            [attr.fill]="selectedNodeIndex===0 ? 'rgba(221,0,49,0.12)' : 'rgba(221,0,49,0.06)'"/>
          <circle cx="94" cy="108" r="22" fill="rgba(221,0,49,0.14)" stroke="rgba(221,0,49,0.3)" stroke-width="1"/>
          <text x="94" y="114" text-anchor="middle" font-size="18" font-family="'Font Awesome 6 Free', sans-serif" fill="#dd0031">&#xf420;</text>
          <text x="94" y="147" text-anchor="middle" font-size="8.5" font-weight="700" fill="rgba(221,0,49,0.8)" font-family="monospace" letter-spacing="0.8">FRONTEND</text>
          <text x="94" y="162" text-anchor="middle" font-size="12" font-weight="700" fill="#f1f5f9" font-family="'DM Sans', sans-serif">Angular UI</text>
          <text x="94" y="177" text-anchor="middle" font-size="10" fill="rgba(148,163,184,0.7)" font-family="'DM Sans', sans-serif">Client App</text>
        </g>

        <!-- ── NODE 1: API Gateway ── -->
        <g class="svg-node" (click)="selectNode(1)" [class.svg-active]="selectedNodeIndex===1" style="cursor:pointer">
          <rect x="240" y="72" width="148" height="116" rx="14"
            fill="rgba(167,139,250,0.06)" stroke="rgba(167,139,250,0.35)" stroke-width="1.5"
            [attr.stroke]="selectedNodeIndex===1 ? '#a78bfa' : 'rgba(167,139,250,0.35)'"
            [attr.fill]="selectedNodeIndex===1 ? 'rgba(167,139,250,0.12)' : 'rgba(167,139,250,0.06)'"/>
          <circle cx="314" cy="108" r="22" fill="rgba(167,139,250,0.14)" stroke="rgba(167,139,250,0.3)" stroke-width="1"/>
          <text x="314" y="114" text-anchor="middle" font-size="16" font-family="'Font Awesome 6 Free', sans-serif" fill="#a78bfa">&#xf0e8;</text>
          <text x="314" y="147" text-anchor="middle" font-size="8.5" font-weight="700" fill="rgba(167,139,250,0.8)" font-family="monospace" letter-spacing="0.8">ROUTING</text>
          <text x="314" y="162" text-anchor="middle" font-size="12" font-weight="700" fill="#f1f5f9" font-family="'DM Sans', sans-serif">API Gateway</text>
          <text x="314" y="177" text-anchor="middle" font-size="10" fill="rgba(148,163,184,0.7)" font-family="'DM Sans', sans-serif">Spring Cloud Gateway</text>
        </g>

        <!-- ── NODE 2: Microservices ── -->
        <g class="svg-node" (click)="selectNode(2)" [class.svg-active]="selectedNodeIndex===2" style="cursor:pointer">
          <rect x="460" y="72" width="148" height="116" rx="14"
            fill="rgba(109,179,63,0.06)" stroke="rgba(109,179,63,0.35)" stroke-width="1.5"
            [attr.stroke]="selectedNodeIndex===2 ? '#6db33f' : 'rgba(109,179,63,0.35)'"
            [attr.fill]="selectedNodeIndex===2 ? 'rgba(109,179,63,0.12)' : 'rgba(109,179,63,0.06)'"/>
          <circle cx="534" cy="108" r="22" fill="rgba(109,179,63,0.14)" stroke="rgba(109,179,63,0.3)" stroke-width="1"/>
          <text x="534" y="114" text-anchor="middle" font-size="16" font-family="'Font Awesome 6 Free', sans-serif" fill="#6db33f">&#xf233;</text>
          <text x="534" y="147" text-anchor="middle" font-size="8.5" font-weight="700" fill="rgba(109,179,63,0.8)" font-family="monospace" letter-spacing="0.8">BACKEND</text>
          <text x="534" y="162" text-anchor="middle" font-size="12" font-weight="700" fill="#f1f5f9" font-family="'DM Sans', sans-serif">Microservices</text>
          <text x="534" y="177" text-anchor="middle" font-size="10" fill="rgba(148,163,184,0.7)" font-family="'DM Sans', sans-serif">Spring Boot + Eureka</text>
        </g>

        <!-- ── NODE 3: PostgreSQL ── -->
        <g class="svg-node" (click)="selectNode(3)" [class.svg-active]="selectedNodeIndex===3" style="cursor:pointer">
          <rect x="680" y="72" width="148" height="116" rx="14"
            fill="rgba(51,103,145,0.06)" stroke="rgba(51,103,145,0.45)" stroke-width="1.5"
            [attr.stroke]="selectedNodeIndex===3 ? '#336791' : 'rgba(51,103,145,0.45)'"
            [attr.fill]="selectedNodeIndex===3 ? 'rgba(51,103,145,0.14)' : 'rgba(51,103,145,0.06)'"/>
          <circle cx="754" cy="108" r="22" fill="rgba(51,103,145,0.18)" stroke="rgba(51,103,145,0.4)" stroke-width="1"/>
          <text x="754" y="114" text-anchor="middle" font-size="16" font-family="'Font Awesome 6 Free', sans-serif" fill="#5b9bd5">&#xf1c0;</text>
          <text x="754" y="147" text-anchor="middle" font-size="8.5" font-weight="700" fill="rgba(91,155,213,0.85)" font-family="monospace" letter-spacing="0.8">DATA LAYER</text>
          <text x="754" y="162" text-anchor="middle" font-size="12" font-weight="700" fill="#f1f5f9" font-family="'DM Sans', sans-serif">PostgreSQL</text>
          <text x="754" y="177" text-anchor="middle" font-size="10" fill="rgba(148,163,184,0.7)" font-family="'DM Sans', sans-serif">Multi-tenant Schema</text>
        </g>

        <!-- ── NODE 4: Docker/K8s ── -->
        <g class="svg-node" (click)="selectNode(4)" [class.svg-active]="selectedNodeIndex===4" style="cursor:pointer">
          <rect x="900" y="60" width="140" height="130" rx="14"
            fill="rgba(50,108,229,0.06)" stroke="rgba(50,108,229,0.35)" stroke-width="1.5"
            [attr.stroke]="selectedNodeIndex===4 ? '#326ce5' : 'rgba(50,108,229,0.35)'"
            [attr.fill]="selectedNodeIndex===4 ? 'rgba(50,108,229,0.12)' : 'rgba(50,108,229,0.06)'"/>
          <circle cx="970" cy="108" r="22" fill="rgba(50,108,229,0.14)" stroke="rgba(50,108,229,0.3)" stroke-width="1"/>
          <text x="970" y="114" text-anchor="middle" font-size="16" font-family="'Font Awesome 6 Free Brands', 'Font Awesome 6 Brands', sans-serif" fill="#326ce5">&#xf395;</text>
          <text x="970" y="147" text-anchor="middle" font-size="8.5" font-weight="700" fill="rgba(50,108,229,0.85)" font-family="monospace" letter-spacing="0.8">CONTAINERS</text>
          <text x="970" y="162" text-anchor="middle" font-size="12" font-weight="700" fill="#f1f5f9" font-family="'DM Sans', sans-serif">Docker / K8s</text>
          <text x="970" y="177" text-anchor="middle" font-size="10" fill="rgba(148,163,184,0.7)" font-family="'DM Sans', sans-serif">Orchestration</text>
        </g>

        <!-- ── NODE 5: CI/CD ── -->
        <g class="svg-node" (click)="selectNode(5)" [class.svg-active]="selectedNodeIndex===5" style="cursor:pointer">
          <rect x="900" y="205" width="140" height="48" rx="10"
            fill="rgba(240,80,50,0.06)" stroke="rgba(240,80,50,0.35)" stroke-width="1.5"
            [attr.stroke]="selectedNodeIndex===5 ? '#f05032' : 'rgba(240,80,50,0.35)'"
            [attr.fill]="selectedNodeIndex===5 ? 'rgba(240,80,50,0.12)' : 'rgba(240,80,50,0.06)'"/>
          <text x="920" y="225" text-anchor="start" font-size="8.5" font-weight="700" fill="rgba(240,80,50,0.85)" font-family="monospace" letter-spacing="0.8">CI/CD</text>
          <text x="920" y="242" text-anchor="start" font-size="11" font-weight="700" fill="#f1f5f9" font-family="'DM Sans', sans-serif">GitHub Actions</text>
        </g>

        <!-- Pulse dots on active node -->
        <circle *ngIf="selectedNodeIndex===0" cx="94" cy="72" r="4" fill="#dd0031" opacity="0.8">
          <animate attributeName="opacity" values="0.8;0.2;0.8" dur="1.5s" repeatCount="indefinite"/>
        </circle>
        <circle *ngIf="selectedNodeIndex===1" cx="314" cy="72" r="4" fill="#a78bfa" opacity="0.8">
          <animate attributeName="opacity" values="0.8;0.2;0.8" dur="1.5s" repeatCount="indefinite"/>
        </circle>
        <circle *ngIf="selectedNodeIndex===2" cx="534" cy="72" r="4" fill="#6db33f" opacity="0.8">
          <animate attributeName="opacity" values="0.8;0.2;0.8" dur="1.5s" repeatCount="indefinite"/>
        </circle>
        <circle *ngIf="selectedNodeIndex===3" cx="754" cy="72" r="4" fill="#336791" opacity="0.8">
          <animate attributeName="opacity" values="0.8;0.2;0.8" dur="1.5s" repeatCount="indefinite"/>
        </circle>
        <circle *ngIf="selectedNodeIndex===4" cx="970" cy="60" r="4" fill="#326ce5" opacity="0.8">
          <animate attributeName="opacity" values="0.8;0.2;0.8" dur="1.5s" repeatCount="indefinite"/>
        </circle>
        <circle *ngIf="selectedNodeIndex===5" cx="970" cy="205" r="4" fill="#f05032" opacity="0.8">
          <animate attributeName="opacity" values="0.8;0.2;0.8" dur="1.5s" repeatCount="indefinite"/>
        </circle>
      </svg>

      <!-- Click hint -->
      <p class="diagram-hint"><i class="fas fa-hand-pointer"></i> Click any node to explore its implementation details</p>
    </div>

    <!-- INSIGHTS PANEL -->
    <div class="insights-panel glass-card" *ngIf="selectedNodeIndex !== null">
      <div class="panel-accent" [style.background]="architectureNodes[selectedNodeIndex].color"></div>
      <div class="insights-content">
        <div class="insights-header">
          <div class="insights-title-row">
            <span class="node-tag"
              [style.background]="architectureNodes[selectedNodeIndex].color + '18'"
              [style.color]="architectureNodes[selectedNodeIndex].color">
              {{ architectureNodes[selectedNodeIndex].type }}
            </span>
            <h3>{{ architectureNodes[selectedNodeIndex].title }}</h3>
          </div>
          <p class="node-purpose">{{ architectureNodes[selectedNodeIndex].purpose }}</p>
        </div>
        <div class="details-grid">
          <div class="detail-box">
            <h5><i class="fas fa-microchip"></i> Technology Stack</h5>
            <div class="tech-tags">
              <span class="tech-tag" *ngFor="let tech of architectureNodes[selectedNodeIndex].techStack">{{ tech }}</span>
            </div>
          </div>
          <div class="detail-box">
            <h5><i class="fas fa-list-check"></i> Core Implementations</h5>
            <ul class="resp-list">
              <li *ngFor="let resp of architectureNodes[selectedNodeIndex].responsibilities" [innerHTML]="resp"></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>
